version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "juliansteenbakker"
  - package-ecosystem: gradle
    directory: "/android"
    schedule:
      interval: "weekly"
    reviewers:
      - "juliansteenbakker"
  - package-ecosystem: gradle
    directory: "/example/android"
    schedule:
      interval: "weekly"
    reviewers:
      - "juliansteenbakker"